# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20160408_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='aggregated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.Notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_aggregate',
            field=models.BooleanField(default=False),
        ),
    ]
