# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20160412_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
