# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notification_emailed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationSubscription',
            new_name='NotificationTypeSubscription',
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
