# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20160414_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='email',
            field=models.BooleanField(default=True),
        ),
    ]
